### ISSUE TITLE
Add the course modules

### ISSUE THREAD

**Issue by OleksiyRudenko** [kottans/git-course#1]
The course must offer learning materials on
 - [x] Linux CLI basics
 - [x] Git basics to maintain student's own projects
 - [x] Git collaboration - to collaborate with others or work on student's own projects from multiple machines
 - [x] Git workflow and GitHub covering PR, code review, conflict resolution matters
 - [x] a workshop for advanced Git users

**Comment by OleksiyRudenko** [comment]
Sources:
- [x] [kottans/frontend](https://github.com/kottans/frontend)
- [x] [kottans/backend](https://github.com/kottans/backend)
- [x] [pygang/bootcamp](https://github.com/py-gang/bootcamp) git modules to take structure from
- [x] [pygang/bootkcamp/issues](https://github.com/py-gang/bootcamp/issues) take extra materials on Git and Linux CLI from

**Comment by sudodoki** [comment]
Possibly might be useful to add reference to something like [git magic](http://www-cs-students.stanford.edu/~blynn/gitmagic/) it has useful things like chapter 8 & appendix A that are not so common to be gathered in the same space
