### ISSUE TITLE
modules/git-workflow-github: add resources on forking

### ISSUE THREAD

**Issue by OleksiyRudenko** [kottans/git-course#14]
- [Fork a repo](https://help.github.com/en/articles/fork-a-repo) - freely experiment with changes without affecting the original project;
- [Sync a repo](https://help.github.com/en/articles/syncing-a-fork) - keep a fork of the repository up-to-date with the upstream repository

**Comment by ipgpt** [comment]
did I solve it right?
https://github.com/kottans/git-course/pull/17

**Comment by ipgpt** [comment]
@OleksiyRudenko please review

**Comment by OleksiyRudenko** [comment]
Hi @ipgpt,
Thank you for your contribution. Will review during the week
