### ISSUE TITLE
Move github-typos.md to kottans/git-workshop-sandbox

### ISSUE THREAD

**Issue by OleksiyRudenko** [kottans/git-course#15]
- [ ] move `modules/github-typos.md` to `kottans/git-workshop-sandbox` repo
- [ ] fix link and instructions in `modules/git-workflow-github.md` as appropriate

**Comment by ipgpt** [comment]
did I solve it right?
https://github.com/kottans/git-course/pull/18
https://github.com/kottans/git-workshop-sandbox/pull/31

**Comment by ipgpt** [comment]
@OleksiyRudenko please review
